[package]
name = "TetrisAttack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-ordinalize = "3.1.12"
rand = "0.8.5"

[dependencies.amethyst]
version = "0.15.3"
features = ["vulkan"]
